[package]
name = "day13"
version = "0.1.0"
authors = ["muvlon <muvlon@hentzes.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring-algorithm = "0.2.2"
