[package]
name = "day7"
version = "0.1.0"
authors = ["muvlon <muvlon@hentzes.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.0"
petgraph = "0.5.1"
string-interner = "0.12.1"
anyhow = "1.0.35"
